name: Discord Message Notify

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      commit_message: CommitMessage
    steps:
    - uses: actions/checkout@v2.4.0
      with:
          ref: ${{ github.head_ref }}
    - name: Get commit message
      id: commit_message
      run: |
        commit_message: "::set-output name=commit_message::$(git log -1 --pretty=format:'%s')"
    - name: Discord Message Notify
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub Bot"
        args: "The ${{ github.event_name }} event was triggered by @${{ github.actor }} with the message: ${{ env.commit_message }}"
