name: Discord Message Notify

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  notify_discord_of_push:
    name: Get Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's head branch
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }} #For pull_request events, GITHUB_REF contains the merge branch (refs/pull/:prNumber/merge).
      - name: Get last notified commit SHA
        run: |
          echo "::set-env name=Last_Notified_SHA::${{ secrets.LAST_NOTIFIED_SHA }}"
      - name: Get commit message
        run: |
          MESSAGE=$(git log --pretty=format:"%s" ${{ env.Last_Notified_SHA }}..HEAD)
          echo "::set-env name=Commit_Message::$MESSAGE"
          echo "::set-env name=New_Notified_SHA::${{ github.sha }}"
      - name: Notify discord
        if: env.Commit_Message != ''
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          args: "${{ github.event_name }} by @${{ github.actor }} \nmessage: ${{ env.Commit_Message }}"
      - name: Save new notified commit SHA
        if: env.Commit_Message != ''
        run: |
          echo "::set-env name=LAST_NOTIFIED_SHA::${{ env.New_Notified_SHA }}"
